#!/usr/bin/env bash

source /opt/ros/kinetic/setup.bash
#export ROS_MASTER_URI=http://192.168.88.239:11311
#export ROS_IP=192.168.88.239
export PYTHONPATH=${PYTHONPATH}:/home/odroid/catkin_ws/src/ros-eurobot-2019/libs
export PATH="${PATH}:/home/odroid/catkin_ws/src/ros-eurobot-2019/scripts"
source /home/odroid/catkin_ws/devel/setup.bash

sleep 5s
export DISPLAY=:0

roslaunch eurobot_main secondary_robot_bt.launch
